baseURL = "https://bl-zhang.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of bl zhang"
theme = "anatole-master"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
themesDir="D:/hugo/myBlogger/themes"
# Enable Disqus
#disqusShortname = ""
profilePicture = "D:/hugo/myBlogger/themes/anatole-master/exampleSite/static/images/profile.jpg"
# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"